### ISSUE TITLE
Failed to install on OSX 

### ISSUE THREAD

**Issue by ghuo** [reasonml/reason-cli#18]
Hi, I'm running into this on an install and I'm stuck. Could you please take a look? Thanks.

```
29979 silly vacuum-fs quitting because other entries in /Users/george/.nvm/versions/node/v7.9.0/lib/node_modules
29980 silly rollbackFailedOptional Finishing
29981 silly runTopLevelLifecycles Finishing
29982 silly install printInstalled
29983 verbose stack Error: reason-cli@1.7.3 postinstall: `./performActualInstallAndFixLinks.sh`
29983 verbose stack Exit status 1
29983 verbose stack     at EventEmitter.<anonymous> (/Users/george/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
29983 verbose stack     at emitTwo (events.js:106:13)
29983 verbose stack     at EventEmitter.emit (events.js:194:7)
29983 verbose stack     at ChildProcess.<anonymous> (/Users/george/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
29983 verbose stack     at emitTwo (events.js:106:13)
29983 verbose stack     at ChildProcess.emit (events.js:194:7)
29983 verbose stack     at maybeClose (internal/child_process.js:899:16)
29983 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
29984 verbose pkgid reason-cli@1.7.3
29985 verbose cwd /Users/george/projects/pg
29986 error Darwin 16.5.0
29987 error argv "/Users/george/.nvm/versions/node/v7.9.0/bin/node" "/Users/george/.nvm/versions/node/v7.9.0/bin/npm" "install" "--verbose" "-g" "git://github.com/reasonml/reason-cli.git#beta-v-1.13.3"
29988 error node v7.9.0
29989 error npm  v4.2.0
29990 error code ELIFECYCLE
29991 error errno 1
29992 error reason-cli@1.7.3 postinstall: `./performActualInstallAndFixLinks.sh`
29992 error Exit status 1
29993 error Failed at the reason-cli@1.7.3 postinstall script './performActualInstallAndFixLinks.sh'.
29993 error Make sure you have the latest version of node.js and npm installed.
29993 error If you do, this is most likely a problem with the reason-cli package,
29993 error not with npm itself.
29993 error Tell the author that this fails on your system:
29993 error     ./performActualInstallAndFixLinks.sh
29993 error You can get information on how to open an issue for this project with:
29993 error     npm bugs reason-cli
29993 error Or if that isn't available, you can get their info via:
29993 error     npm owner ls reason-cli
29993 error There is likely additional logging output above.
29994 verbose exit [ 1, true ]
```

**Comment by jordwalke** [comment]
Thanks. Curious do you have `python2` installed?

**Comment by nsklyarov** [comment]
thats help me

**Comment by ghuo** [comment]
Jordan, looks like I had a `/usr/local/bin/python2` that was incorrectly softlinked on my system (it existed but failed to actually run python), which seemed to cause it. Thanks for the pointer. I manually fixed it to `/usr/bin/python2.7' and got to `npm info ok`. I'll follow up if I see more issues.
