### ISSUE TITLE
Unable to install reason-cli in a virtual machine behind a proxy

### ISSUE THREAD

**Issue by tddsg** [reasonml/reason-cli#22]
Hi there,

I'm trying to install `reason-mli` in a VirtualBox Linux machine, which is behind a proxy, but it somehow doesn't work. I followed this tutorial ttps://github.com/facebook/reason/tree/master/editorSupport/emacs to run the following command:

    npm install -g git://github.com/reasonml/reason-cli.git

My proxy configuration list is something like below:

```
; userconfig /home/trungtq/.npmrc
http-proxy = "http://www....:80"
https-proxy = "http://www....:80/"
proxy = "http://www.....:80/"
registry = "http://registry.npmjs.org/"
strict-ssl = false
```

Here is the error after running `npm install -g git://github.com/reasonml/reason-cli.git`

```
npm ERR! git clone --template=/home/trungtq/.npm/_git-remotes/_templates --mirror git://github.com/reasonml/reason-cli.git /home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f: Cloning into bare repository '/home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f'...
npm ERR! git clone --template=/home/trungtq/.npm/_git-remotes/_templates --mirror git://github.com/reasonml/reason-cli.git /home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/trungtq/.npm/_git-remotes/_templates --mirror git://github.com/reasonml/reason-cli.git /home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f: github.com[0: 192.30.255.112]: errno=No route to host
npm ERR! git clone --template=/home/trungtq/.npm/_git-remotes/_templates --mirror git://github.com/reasonml/reason-cli.git /home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f: github.com[1: 192.30.255.113]: errno=No route to host
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "git://github.com/reasonml/reason-cli.git"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/trungtq/.npm/_git-remotes/_templates --mirror git://github.com/reasonml/reason-cli.git /home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f
npm ERR! Cloning into bare repository '/home/trungtq/.npm/_git-remotes/git-github-com-reasonml-reason-cli-git-90858a2f'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.255.112]: errno=No route to host
npm ERR! github.com[1: 192.30.255.113]: errno=No route to host
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/trungtq/workspace/explore/reports/npm-debug.log
```
Could you please advise how I can handle this error?
Thanks!

**Comment by jordwalke** [comment]
Can you clone anything from github behind the proxy?

**Comment by tddsg** [comment]
I can clone by only using the https link: `git clone https://github.com/reasonml/reason-cli.git`
The link with git:// doesn't work to me:

```
trungtq@lmint ~/workspace/explore/reports $ git clone git://github.com/reasonml/reason-cli.git
Cloning into 'reason-cli'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=No route to host
github.com[1: 192.30.255.113]: errno=No route to host

```

**Comment by tddsg** [comment]
I found a work around to clone the git repo:

`
git config --global url.https://github.com/.insteadOf git://github.com/
`

Hower, I encounter another issue like below:

```
> reason-cli@1.7.3 postinstall /usr/local/lib/node_modules/reason-cli
> ./performActualInstallAndFixLinks.sh

/usr/local/lib/node_modules/reason-cli/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/trungtq/.cache/yarn'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Function.sync (/usr/local/lib/node_modules/reason-cli/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/reason-cli/node_modules/esy/bin/yarn.js:30:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "git://github.com/reasonml/reason-cli.git"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! reason-cli@1.7.3 postinstall: `./performActualInstallAndFixLinks.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reason-cli@1.7.3 postinstall script './performActualInstallAndFixLinks.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reason-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./performActualInstallAndFixLinks.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reason-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reason-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/trungtq/workspace/explore/reports/npm-debug.log

```

I install reason-cli using `sudo` right, why there is the permission issue at the below line?

`
Error: EACCES: permission denied, mkdir '/home/trungtq/.cache/yarn'
`

**Comment by jordwalke** [comment]
It seems you cannot write to your home directory. Is that the case? It currently uses yarn under the hood - which is a popular package manager, and it write to the home directory `~/.cache`. Are you also unable to use yarn on your machine?

**Comment by tddsg** [comment]
Yes, I install yarn by the following command: `sudo apt install cmdtest`

Here is the result when running `yarn`:

```
trungtq@lmint ~/workspace/explore/reports $ yarn
ERROR: There are no scenarios; must have at least one.

```

**Comment by jordwalke** [comment]
we have just found a way to do "packed" installations of the entire reason-cli. I estimate about a week until that is out. That will remove yarn, and effectively just be a giant tarball for you to download via npm.
